version: "3.9"  # optional since v1.27.0
services:
  server: 
    image: "openvidu/openvidu-server-kms:2.17.0"    
    ports:
      - "4443:4443"
    environment:
      - "OPENVIDU_SECRET=MY_SECRET"
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on: 
      - server  
volumes:
  logvolume01: {}
